### ISSUE TITLE
Which layer is MAG used?

### ISSUE THREAD

**Issue by fly-pandas** [WasifurRahman/BERT_multimodal_transformer#17] opened 2021-01-25 01:37 UTC
Can you tell me which layer MAG is applied？I only found that MAG is used after Embedding, not the first to 12th layers. Thank you very much!

**Comment by RE-N-Y** [comment] 2021-01-25 10:05
Duplicate of #9. Please refer to the discussion in the linked issue. Feel free to re-open the issue if any question persists.

**Closed as completed by RE-N-Y** 2021-01-25 10:05 UTC
