### ISSUE TITLE
Data for mosei

### ISSUE THREAD

**Issue by PierreColombo** [WasifurRahman/BERT_multimodal_transformer#8] opened 2020-11-03 11:31 UTC
Hello,
Thanks for your great work!
Where is it possible to get the data for reproducing the results on mosei ?
Kindest regards

**Comment by RE-N-Y** [comment] 2020-11-04 08:03
[CMU Mosei](https://github.com/A2Zadeh/CMU-MultimodalSDK) data is available here. But, I know that the dataset went through several updates since we submitted our paper to ACL, so performance maybe slightly different now.

If more people would like to reproduce the results on MOSEI or on their own dataset, I will add MOSEI to the repo and write a guide on how .pickle file should be formatted.

**Comment by PierreColombo** [comment] 2020-11-04 08:08
Hello, 
Is it possible to have the details on the pickle file ?
Kindest regards

**Comment by RE-N-Y** [comment] 2020-11-07 01:14
Hi sorry for the delay, let me check on the format, and I will include it in the README.md in a day or two

**Comment by RE-N-Y** [comment] 2020-11-08 10:12
@PierreColombo Just fixed the typos and added documentation on data format. Let me know if the format is not clear or if you have suggestions. If not feel free to close the issue.

**Comment by ky941122** [comment] 2020-11-09 09:08
> [CMU Mosei](https://github.com/A2Zadeh/CMU-MultimodalSDK) data is available here. But, I know that the dataset went through several updates since we submitted our paper to ACL, so performance maybe slightly different now.
> 
> If more people would like to reproduce the results on MOSEI or on their own dataset, I will add MOSEI to the repo and write a guide on how .pickle file should be formatted.

@RE-N-Y  Hi, I'm interested in reproducing results on MOSEI too. But the data provided by cmu-sdk does not include the raw text and matching the raw text to other sdk-features and making it in the same format as the mosi data you provided in the repo will take some work. 
So, could you supply the script that you making data? Since the .pickle file of MOSEI may too big to github.

**Comment by RE-N-Y** [comment] 2020-11-09 12:56
@WasifurRahman  Do you know if you can add .pickle file or python script you used to compile MOSEI pickle? I currently don't have access to it

**Comment by EmileChapuis** [comment] 2020-11-09 15:05
> [CMU Mosei](https://github.com/A2Zadeh/CMU-MultimodalSDK) data is available here. But, I know that the dataset went through several updates since we submitted our paper to ACL, so performance maybe slightly different now.
> 
> If more people would like to reproduce the results on MOSEI or on their own dataset, I will add MOSEI to the repo and write a guide on how .pickle file should be formatted.

Thanks for your work. Indeed I would also like to have access to your version of MOSEI.

**Comment by GuillaumeStaermanML** [comment] 2020-11-09 19:37
I would be interested ro reproduce your results on MOSEI too.

**Comment by tdinkar** [comment] 2020-11-10 09:24
Hello, I found the ACL paper very interesting! 
I would also like to request access to your version of the CMU-MOSEI dataset. 
Thank you.

**Comment by LucienMaman** [comment] 2020-11-10 09:52
Hello, 
Thank you for your work! I would also be interested to reproduce your results on MOSEI.

**Comment by Hamid-Jalalzai** [comment] 2020-11-10 10:25
Hello, I found your work very interesting. If possible, I would like to request access to your version of the CMU-MOSEI dataset. Thank you in advance!

**Comment by RE-N-Y** [comment] 2020-11-10 13:01
Thank you! Let me talk to the authors, we will try to get the MOSEI added in a few weeks. I will update the progress on this thread. Initially, we will post the .pickle file for MOSEI, but it may take quite a while to re-run the hyper-parameter tuning on MOSEI since it's significantly larger than MOSI.

**Comment by PierreColombo** [comment] 2020-11-10 13:55
Hey thanks a lot,
I have plenty of computational power :) . 
We are more interrested in comparing improvement induced by our methods than absolute values. Do you believe you could give us a pickle shortly ? We are aiming for naacl in two weeks.

**Comment by RE-N-Y** [comment] 2020-11-11 03:26
@PierreColombo In that case, let me re-compile MOSEI pickle into a compatible format in a day or two. Perhaps when you run the experiments, you can let us know if it achieves intended performance as well 😄

**Closed as completed** 2020-11-12 00:24 UTC
Labels: enhancement

**Comment by RE-N-Y** [comment] 2020-11-12 00:31
Everyone, MOSEI has been officially added to the master branch with a few code refactoring. The code has been tested on GPU.
For details, on pre-processing applied on MOSEI and code changes refer to the linked pull request #10.

I have added a `examine.ipynb` which should make it easy to examine / validate the dataset. 😎 
**Please check the new instructions for downloading the datasets and configuring runs!**

@PierreColombo good luck with NAACL submission and feel free to re-open the issue if any problem still persists.

**Comment by PierreColombo** [comment] 2020-11-12 07:44
Many thanks :) i really appreciate 👍

**Comment by ky941122** [comment] 2020-11-12 10:44
@RE-N-Y 
Hi, It seems that the mosei dataset can not be run directly. It throws `ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 47 and the array at index 1 has size 35`

**Comment by RE-N-Y** [comment] 2020-11-12 11:13
@ky941122 
In `global_config.py`, make sure that you're using the modality dimensions for MOSEI. Perhaps, I should've made that more clear in the README.

**Comment by ky941122** [comment] 2020-11-13 02:23
@RE-N-Y 
Oh, thanks, I have not read the latest README yet.
